### ISSUE TITLE
Support installation of 64-bit GHC

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#15]

**Comment by gregwebs** [comment]
Good enough to put in the README now?

**Comment by snoyberg** [comment]
I see no objection, so I've done so. The README now links to 7.8.3 32-bit and 7.8.4 64-bit.

@ndmitchell I'm in the process of cleaning up my 64-bit changes, and then I'll send them as a PR so you can review before they land on master.

**Comment by snoyberg** [comment]
OK, pull request open: #21.
