### ISSUE TITLE
Upgrade to the latest cabal.exe

### ISSUE THREAD

**Issue by ndmitchell** [fpco/minghc#16]
Blocked on https://github.com/haskell/cabal/issues/2279

**Comment by ndmitchell** [comment]
Maybe we should be building our own Cabal packages ourselves? It seems likely we're going to be building our own happy and alex, so building our own Cabal too doesn't seem too onerous. Does require a Windows machine with `network` installed on it, which at the start of this project was a real pain, but now it's no big deal :)

**Comment by snoyberg** [comment]
I have no problem with that. If you create an executable, I'll be happy to upload it to S3 (like you did for alex/happy). I just don't have access to a Windows build machine right now (my VMs got wiped out with a system reinstall).

**Comment by ndmitchell** [comment]
Version 1.22 is now out, and that's at https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz, so I guess we can upgrade right passed this missing version.

**Comment by ndmitchell** [comment]
I just did a `cabal install` and it said it built version 1.22.1.1, but it doesn't seem to have actually done so. Relatively confused, but there might be a newer version out there.

**Comment by snoyberg** [comment]
Newest version of minghc has the newest cabal, safe to close?

**Comment by ndmitchell** [comment]
Yep!
