### ISSUE TITLE
Cabal has some questionable defaults. Should minghc install alternate config?

### ISSUE THREAD

**Issue by tejon** [fpco/minghc#17]
In particular, I'm thinking about the default to only vanilla libraries. That's a lot of painful reinstalling if you don't know, or forget, to change it immediately. http://www.vex.net/~trebla/haskell/cabal-cabal.xhtml makes good suggestions in general.

I'm not 100% sure this is in scope for minghc, since it doesn't seem to otherwise make any modifications to individual packages; but it does fit the guiding theme IMO.

**Comment by snoyberg** [comment]
Closing this issue as "unfortunately wontfix"
