### ISSUE TITLE
cabal update APPCRASH Windows Server 2008 R2

### ISSUE THREAD

**Issue by bhillis** [fpco/minghc#23]
A fresh installation of Windows Server 2008 R2, when minghc-7.8.3 or minghc-7.8.4-x86_64 is installed, running cabal update starts the process but on reaching

Downloading the latest package list from hackage.haskell.org

the following appears

![image](https://cloud.githubusercontent.com/assets/10448814/5661916/a0fac64a-9785-11e4-8e81-e66a535a3cf4.png)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	cabal.exe
  Application Version:	0.0.0.0
  Application Timestamp:	53d6efb8
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7bafa
  Exception Code:	40010006
  Exception Offset:	0000b727
  OS Version:	6.1.7601.2.1.0.272.7
  Locale ID:	1033
  Additional Information 1:	53cb
  Additional Information 2:	53cb7be0fb852ae44dcdf0df9b24117f
  Additional Information 3:	993a
  Additional Information 4:	993ac5f6525bc97f4b381e31cd2c5591

Tried installing into the default path and a new path. Tried as Administrator or normal user. Tried with custom config from Stackage. All crash in the same way.

Just to confirm that it wasn't a bad download, installing on Windows 7 32-bit & Windows 8 64-bit worked without issue.

**Comment by snoyberg** [comment]
We just [get cabal.exe from the cabal website](https://github.com/fpco/minghc/blob/master/Config.hs#L35). Can you try downloading the executable from:

https://www.haskell.org/cabal/release/cabal-install-1.20.0.3/cabal-1.20.0.3-i386-unknown-mingw32.tar.gz

and see if you have similar problems?

**Comment by bhillis** [comment]
Direct cabal download also crashes. Looks like I have to report the bug somewhere else then.
