### ISSUE TITLE
Distinguish between 32-bit and 64-bit switchers

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#27]
When the same version of 32-bit and 64-bit GHC are installed side by side, the switcher script name will be ambiguous between the two. Perhaps we could add `-x64` to the end of the 64-bit switcher?

**Comment by ndmitchell** [comment]
Great idea, and I think we should go even further. Each install should add `minghc.bat`, `minghc-7.8.3.bat`, `minghc-7.8.bat`, `minghc-7.8-32.bat` and `minghc-7.8.3-32.bat`. The idea being you can be as specific or vague as you want, and your `$PATH` will pick the "first" matching one for you. It's like distributed ordered pattern-matching :).

**Comment by 3noch** [comment]
My brain :boom:

**Comment by ndmitchell** [comment]
So we now have `minghc-7.8.3.bat` and `minghc-7.8.3-32.bat`. I'm still a fan of adding `minghc.bat`, `minghc-32.bat`, `minghc-7.8.bat` and `minghc-7.8-32.bat`. I'm fed up of remembering what minor version each GHC release got to, and which I have installed locally (complicated by the fact that I sometimes use GHC point releases which don't exist outside work).

**Comment by 3noch** [comment]
I would like to add this too, but I'm not sure the best approach at dividing the GHC version into its parts.

**Comment by ndmitchell** [comment]
[`dropEnd 2`](https://hackage.haskell.org/package/extra-1.1/docs/Data-List-Extra.html#v:dropEnd) works, as does [`wordsBy (== '.')`](https://hackage.haskell.org/package/extra-1.1/docs/Data-List-Extra.html#v:dropEnd).

**Comment by ndmitchell** [comment]
Note we already have a dependency on the extra library, so that is ideal.

**Comment by 3noch** [comment]
Should I put each variation into a new NSIS constant?

**Comment by ndmitchell** [comment]
You can do, but I don't think it's necessary. I think I'd probably not have put ARCH_ABBR into a constant, but certainly doing so was following the existing pattern. Either works for me.

**Comment by ndmitchell** [comment]
I think once this and #24 are resolved we should probably think about respinning all installers.

**Comment by ndmitchell** [comment]
All solved with #36 I believe.

**Comment by ndmitchell** [comment]
While testing I spotted a trailing `.bat` was missing from the switched. I added that and it then all works great.

**Comment by 3noch** [comment]
@ndmitchell Thanks for fixing! I'm ashamed that I forgot to mention I didn't test it due to some build failure.

**Comment by ndmitchell** [comment]
No problem at all - took seconds to fix. What was the build issue? We could probably make it easier to build by checking for the required executables and if missing say where they can be found.

**Comment by 3noch** [comment]
Here's what I get:

```
Error when running Shake build system:
* minghc-7.10.1-i386.exe
* .cabal-1.22.2.0
user error (Development.Shake.cmd, system command failed
Command: tar zxfv cabal-1.22.2.0.tar.gz -C bin/bin
Exit code: 2
Stderr:
"tar": Archive value 197609 is out of uid_t range 0..65535
"tar": Archive value 197609 is out of gid_t range 0..65535
"tar": Exiting with failure status due to previous errors
)
```

**Comment by ndmitchell** [comment]
Here's my version of tar:

    C:\Neil>tar --version
    bsdtar 2.4.12 - libarchive 2.4.12

I believe I got it from http://gnuwin32.sourceforge.net/packages/libarchive.htm, then renamed `bsdtar.exe` to `tar.exe`. I often do that as the standard tar you can get from many places sometimes upsets Cabal (its been random, and I'm not even sure Cabal uses tar.exe anymore, but force of habit now).
