### ISSUE TITLE
compile error network 0.2.0.6

### ISSUE THREAD

**Issue by KeesBleijenberg** [fpco/minghc#29]
I tried to use minGHC. I'am working on Windows 7 64 bits. I removed GHC and all packets from my computer as described in https://www.fpcomplete.com/user/varosi/recipes/haskell-on-windows-recipe-1 
I installed installed minGHC-7.8.3 (32 bits). Checked the path. cabal has version 1.20.0.3. I didn't add the switcher to the path.
cabal update (a new default config is written)
cabal install alex happy cabal-install-1.20.0.6 and I get errors (see below). minGHC can't compile network-2.0.6.2. What can I do?

Kees

Resolving dependencies...
Configuring network-2.6.0.2...
Configuring alex-3.1.4...
Configuring happy-1.19.5...
Building alex-3.1.4...
Building happy-1.19.5...
Installed alex-3.1.4
Installed happy-1.19.5
Failed to install network-2.6.0.2
Build log ( C:\Users\kees\AppData\Roaming\cabal\logs\network-2.6.0.2.log ):
Configuring network-2.6.0.2...
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
checking build system type... i686-pc-mingw32
checking host system type... i686-pc-mingw32
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for unistd.h... (cached) yes
checking winsock2.h usability... yes
checking winsock2.h presence... yes
checking for winsock2.h... yes
checking ws2tcpip.h usability... yes
checking ws2tcpip.h presence... yes
checking for ws2tcpip.h... yes
checking arpa/inet.h usability... no
checking arpa/inet.h presence... no
checking for arpa/inet.h... no
checking netdb.h usability... no
checking netdb.h presence... no
checking for netdb.h... no
checking netinet/in.h usability... no
checking netinet/in.h presence... no
checking for netinet/in.h... no
checking netinet/tcp.h usability... no
checking netinet/tcp.h presence... no
checking for netinet/tcp.h... no
checking sys/socket.h usability... no
checking sys/socket.h presence... no
checking for sys/socket.h... no
checking sys/uio.h usability... no
checking sys/uio.h presence... no
checking for sys/uio.h... no
checking sys/un.h usability... no
checking sys/un.h presence... no
checking for sys/un.h... no
checking for readlink... no
checking for symlink... no
checking for struct msghdr.msg_control... no
checking for struct msghdr.msg_accrights... no
checking for struct sockaddr.sa_len... no
checking for in_addr_t in netinet/in.h... no
checking for SO_PEERCRED and struct ucred in sys/socket.h... no
checking for getpeereid in unistd.h... checking for getpeereid... no
checking for _head_libws2_32_a in -lws2_32... yes
checking for getaddrinfo... no
checking for getaddrinfo if WINVER is 0x0501... yes
checking for gai_strerror... no
checking whether AI_ADDRCONFIG is declared... no
checking whether AI_ALL is declared... no
checking whether AI_NUMERICSERV is declared... no
checking whether AI_V4MAPPED is declared... no
checking whether IPV6_V6ONLY is declared... yes
checking whether IPPROTO_IP is declared... yes
checking whether IPPROTO_TCP is declared... yes
checking whether IPPROTO_IPV6 is declared... yes
checking for sendfile in sys/sendfile.h... no
checking for sendfile in sys/socket.h... no
checking for gethostent... no
checking for accept4... no
configure: creating ./config.status
./configure: line 4864: test: too many arguments
./configure: line 4864: test: too many arguments
./configure: line 4864: test: too many arguments
./configure: line 4864: test: too many arguments
./configure: line 4864: test: too many arguments
./configure: line 4864: test: too many arguments
configure: error: could not make ./config.status
cabal: Error: some packages failed to install:
HTTP-4000.2.19 depends on network-2.6.0.2 which failed to install.
cabal-install-1.20.0.6 depends on network-2.6.0.2 which failed to install.
network-2.6.0.2 failed during the configure step. The exception was:
ExitFailure 1

**Comment by ndmitchell** [comment]
I've no idea about this, and never seen it. I wonder if this is an issue for MinGHC or the network people such as @tibbe? @KeesBleijenberg, can you show us line 4864 of your configure script (do `cabal unpack network`, `cd network-...`, `cabal configure` so it shows up somewhere expected`). Mine is:

    if test $ac_delim_n = $ac_delim_num; then

So `test` taking too many arguments seems plausible for that line. Not sure how we find out what `$ac_delim_n` is, perhaps a print on that line? (I've never peered inside a configure script before.)

**Comment by KeesBleijenberg** [comment]
Neil,

 

Thanks for your help.

After a lot of hesitation I wiped my Haskell environment a week ago and installed minGhc. Adding packages with cabal failed immediatly on networks. I’ve posted that problem a few days ago.  Unfortunatly I have to move on. I waited a few days and reinstalled the Haskell platform.  So I can’t help you with debugging anymore. I’ve installed minGhc on another Windows computer, but on that machine everything went fine.

 

Meanwhile there is another problem.  Ghc 7.8.3 goes out of memory when I do a make with –O2 on a big source file. Carter Schonwald said that 7.8.4 solves this problem. But I can’t move to 7.8.4 because it is 64 bits. So I am hoping for a 32 bits version of 7.8.4 on Stackage (preferred) or  on the Haskell Platform. In both cases I have to wipe ghc again (more difficult then it sounds).  If Stackage would have a 32 bits version of 7.8.4, the same problem with the minGhc compiler would probably pop up and maybe you could find the cause of the problem.

So, as soon as I get the error again I’ll let you know.

 

Kees

 

 

 

Van: Neil Mitchell [mailto:notifications@github.com] 
Verzonden: zondag 8 maart 2015 10:44
Aan: fpco/minghc
CC: KeesBleijenberg
Onderwerp: Re: [minghc] compile error network 0.2.0.6 (#29)

 

I've no idea about this, and never seen it. I wonder if this is an issue for MinGHC or the network people such as @tibbe <https://github.com/tibbe> ? @KeesBleijenberg <https://github.com/KeesBleijenberg> , can you show us line 4864 of your configure script (do cabal unpack network, cd network-..., cabal configure so it shows up somewhere expected`). Mine is:

if test $ac_delim_n = $ac_delim_num; then

So test taking too many arguments seems plausible for that line. Not sure how we find out what $ac_delim_n is, perhaps a print on that line? (I've never peered inside a configure script before.)

—
Reply to this email directly or view it on GitHub <https://github.com/fpco/minghc/issues/29#issuecomment-77741136> .Beschrijving: Afbeelding verwijderd door afzender.

No virus found in this message.
Checked by AVG - www.avg.com
Version: 2015.0.5751 / Virus Database: 4299/9258 - Release Date: 03/09/15

**Comment by ndmitchell** [comment]
GHC 7.8.4 for Win32 is currently delayed - I'm waiting on it as well, but @thoughtpolice is working on it, so hopefully not too long.

As soon as it is out, MinGHC will appear. Haskell Platform is likely to be at least months behind that.

**Comment by ndmitchell** [comment]
Oh, and don't worry about wiping everything - thanks for the report, it was useful anyway, I'm sure it will happen to someone else at some point (and if it doesn't, even better!)

**Comment by phongphan** [comment]
I have encountered this issue too.

In my case, it is because the content of the `$ac_delim_n` and/or `$ac_delim_num` contains white spaces (Eg. `62 lines match`).

It turns out the configure script invoke the wrong `grep` on my machine (Borland's grep).
I have fixing it by changing the PATH order to ensure the script invoke provided `grep`.
Eg.
    `PATH=C:\minghc-7.10.1-i386\git-2.4.0.1\usr\bin;%PATH%`

Quote `$ac_delim_n` and `$ac_delim_num` as shown below also work, but it might hide the real bugs.
`if test "$ac_delim_n" = "$ac_delim_num"; then`

Hope this helps

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. All the issues are probably PATH issues, which Stack handles way better.
