### ISSUE TITLE
GLUT is not installable with missing c lib errors

### ISSUE THREAD

**Issue by stonetoad** [fpco/minghc#31]
This is an issue is because GLUT is in the Haskell Platform, and most of the answers on the internet I found told you to just install the HP.

I actually 'accidentally' fixed my problem while working on typing up this issue's details.  So I'll list the steps I took so at the least this issue itself will provide documentation.

I used the freeglut binaries from http://www.transmissionzero.co.uk/software/freeglut-devel/

The ghc looks under "C:\Program Files\MinGHC-x.y.z\ghc.x.y.z\mingw\" in the lib and include subdirectories for the c libraries and include files.  (I didn't find this explicitly documented anywhere)

The key thing I find basically by accident is you must copy(rename?) libfreeglut.a to libglut32.a

This gets GLUT to install fine.  ~~Unfortunately I can't actually test if it works properly since gloss doesnt support ghc 7.10 yet (base == 4.7.* dependency)~~ [Tested a basic program with 7.8.4 64bit and it runs fine once I remembered to install the DLL]

~~I'm not sure how to apply this to the x64 ghc's dirs either.~~ It looks like for 64bit you need to put the x64bit freeglut librarys under  mingw\x86_64-w64-mingw32\ instead of just mingw.

[Edit: You also need rename the DLL to glut32.dll and put it in the directory with your project.  It didn't seem to work when I put it in the system directories, but maybe I did something wrong]

**Comment by snoyberg** [comment]
This sounds like something that would be a good Wiki page or other piece of help documentation. I'm not reading anything that's a bug in MinGHC. Am I mistaken?

**Comment by tejon** [comment]
@snoyberg That's how I'm reading it too, but it could fit in well with the #25 discussion.

**Comment by stonetoad** [comment]
Certainly a wiki page would solve this issue to my mind, as long as there's a clear link from the project readme so it's easy to find.  If someone who knows more can verify that what I did seems reasonable, I'd be willing to write the page up.

I notice there's also some instructions for SDL2 workarounds that @tejon posted in the #25 discussion that should probably get documented as well.

Initially i was going to post it into the #25 discussion but decided that since it was about a Haskell Platform package that it was a slightly different situation.  Initially I was quite surpized that it didn't compile because the readme states "It does not provide all the packages included with the Haskell Platform, but it does provide an environment where you can install those packages."

**Comment by ndmitchell** [comment]
@stonetoad - your offer of a wiki page would be most appreciated. Either on the Haskell wiki, or a markdown file submitted to this project as a pull request (I think I'd prefer the latter, but I'm not too fussed really). We'd certainly link it somewhere.

Agreed, we care slightly more about this one because it is in the platform, but again, I'm not sure we want to actually bundle the necessary pieces. Having a tool that did the right things would be cool, e.g. `cabal install glut-install && glut-install`, but its not something I'd personally be interested in, having never used glut.

**Comment by snoyberg** [comment]
@stonetoad I just noticed that you opened a PR for this. Unfortunately, you opened the PR against your own copy of the repo, not this copy, which is why no one commented on it. Could you open a new PR?

**Comment by stonetoad** [comment]
Woops, bit of a facepalm there.  It looks like I did it right this time!
