### ISSUE TITLE
Linking error with network-2.6.0.2 while building Idris

### ISSUE THREAD

**Issue by fspeech** [fpco/minghc#32]
```
Linking dist/dist-sandbox-ca386853\build\idris\idris.exe ...
...\proj\haskell\idris\.cabal-sandbox\i386-windows-ghc-7.8.3\network-2.6.0.2/libHSnetwork-2.6.0.2.a(HsNet.o):HsNet.c:(.text+0x1c): undefined reference to `getnameinfo'
...\proj\haskell\idris\.cabal-sandbox\i386-windows-ghc-7.8.3\network-2.6.0.2/libHSnetwork-2.6.0.2.a(HsNet.o):HsNet.c:(.text+0x28): undefined reference to `getaddrinfo'
...\haskell\idris\.cabal-sandbox\i386-windows-ghc-7.8.3\network-2.6.0.2/libHSnetwork-2.6.0.2.a(HsNet.o):HsNet.c:(.text+0x34): undefined reference to `freeaddrinfo'
collect2: ld returned 1 exit status
cabal.exe: Error: some packages failed to install:
idris-0.9.17.1 failed during the building phase. The exception was:
ExitFailure 1
```

Do I need to pass additional flags to cabal? I am building from inside a MSYS2 terminal. Not sure if that could cause confusion.

**Comment by fspeech** [comment]
Just verified that I get the same errors when building from the msys1 terminal that comes with MinGHC. I have other gcc in my path but I assume GHC uses its own version.

**Comment by ndmitchell** [comment]
We aren't expecting people to build from any type of MSYS terminal, just standard windows prompt. If you start a Windows shell, type `minghc-7.8.3` then then `cabal install network` does that work? See #33 for more debugging steps.

**Comment by fspeech** [comment]
Yes that appears to be where the problem was. I run ```cabal install --reinstall network``` under a regular Windows prompt and now the linking with network goes through under both Windows and MSYS prompts. So that is good to know. Idris build still fails for me but it doesn't look like a MinGHC issue anymore so I will close this issue. Thanks for the help.
