### ISSUE TITLE
Unable to install c2hs and anything else relying on language-c

### ISSUE THREAD

**Issue by fegu** [fpco/minghc#38]
Unsure what is problem vs symptom here.

Motivation: language-c is a requirement of c2hs (which is a requirement of opencl). It fails to install.

My system: fresh Windows 10 with MinGHC for GHC7.10.1 64bit. The only other packages installed are cabal install alex, happy and network, which all were installed ok. No cygwin, everything done in Windows command window.

The alex.exe in C:\Program Files\MinGHC-7.10.1\bin is 3.1.3.
The alex.exe in C:\Users\FinnEspen\AppData\Roaming\cabal\bin is alex 3.1.4.

Build log:

C:\Users\FinnEspen>cabal install language-c
Resolving dependencies...
Configuring language-c-0.4.7...
Building language-c-0.4.7...
Failed to install language-c-0.4.7
Build log ( C:\Users\FinnEspen\AppData\Roaming\cabal\logs\language-c-0.4.7.log ):
Building language-c-0.4.7...
Preprocessing library language-c-0.4.7...
alex.exe: C:\Documents and Settings\IEUser\Application Data\cabal\i386-windows-ghc-7.8.3\alex-3.1.3/AlexTemplate-ghc-nopred: openFile: does not exist (No such file or directory)
cabal: Error: some packages failed to install:
language-c-0.4.7 failed during the building phase. The exception was:
ExitFailure 1

Note that alex complains about a non-existing path (there is no IEUser) and is looking for something belonging to the i386 version of ghc 7.8.3 - which has never been installed.

**Comment by ndmitchell** [comment]
Sorry @fegu, this is a known issue, tracked in https://github.com/fpco/minghc/issues/24 - rm your `alex` and `happy` and `cabal install` them and it should work.

**Comment by fegu** [comment]
ok, I guess I should have searched a bit more first. I removed alex and happy from c:\program files\minghc-7.10.1\bin and everything worked. No need to reinstall as Windows now found the installed versions in the lower priority path.
