### ISSUE TITLE
msys-1.0.1 bash shell doesn't work under Wine on Linux (freezes)

### ISSUE THREAD

**Issue by erikd** [fpco/minghc#39]
I'm pretty sure fixing this would be really low on your list or priorities, but I thought I submit it anyway.

The installer is quite happyt to work under windows and the installed `ghc.exe` binary can compile a simple "Hello World" program which also runs quite happily under Wine.

However, since I really interested in compiling GHC for Windows under Wine I tried running the `bash.exe` binary that is installed as part of Msys. Unfortunately that binary just freezes the terminal.

**Comment by snoyberg** [comment]
Are you able to check if the same behavior exists for just installing msys and running bash?

**Comment by erikd** [comment]
I did try grabbing installing `MSYS-1.0.11.exe` but that failed complaining about the fact that Msys was already installed. I then tried un-install MinGHC, but Msys still would not install (same problem).

I did however manage to grab a `bash.exe` from `win-bash` (http://win-bash.sourceforge.net/) zip file and that works. I then re-installed MinGHC and copied the working `bash.exe` over the one in MinGHC.

**Comment by ndmitchell** [comment]
I'd consider Wine "unsupported", since the bugs that are encountered are unlikely to be ones we can do anything about. The ultimate goal of compiling GHC from within MinGHC is a good one, and once that works, we can see if we got lucky about Wine or not.
