### ISSUE TITLE
Linking error with network-2.6.0.2 while building Pandoc under Command Prompt

### ISSUE THREAD

**Issue by fspeech** [fpco/minghc#42]
Last time I had similar troubles while building Idris (#32) which was resolved by building under a Command Prompt, this time not so lucky. The error messages are similar:
```
In-place registering pandoc-1.13.2.1...
Preprocessing executable 'pandoc' for pandoc-1.13.2.1...
[1 of 1] Compiling Main             ( pandoc.hs, dist\dist-sandbox-ad34cd67\build\pandoc\pandoc-tmp\Main.o )
Linking dist/dist-sandbox-ad34cd67\build\pandoc\pandoc.exe ...
...\proj\haskell\hakyll\.cabal-sandbox\i386-windows-ghc-7.8.3\network-2.6.0.2/libHSnetwork-2.6.0.2.a(HsNet.o):HsNet.c:(.text+0x1c): undefined reference to `getnameinfo'
...\proj\haskell\hakyll\.cabal-sandbox\i386-windows-ghc-7.8.3\network-2.6.0.2/libHSnetwork-2.6.0.2.a(HsNet.o):HsNet.c:(.text+0x28): undefined reference to `getaddrinfo'
...\proj\haskell\hakyll\.cabal-sandbox\i386-windows-ghc-7.8.3\network-2.6.0.2/libHSnetwork-2.6.0.2.a(HsNet.o):HsNet.c:(.text+0x34): undefined reference to `freeaddrinfo'
collect2: ld returned 1 exit status
```
In the Idris case I was building off a local git clone of Idris, while this time I am running a straight cabal install. Don't know if that made the difference.

**Comment by fspeech** [comment]
I tried with ```cabal unpack pandoc``` and then build locally and it had the same problems. Does this indicate that my network package was built incorrectly?

**Comment by fspeech** [comment]
I am able to cabal build and install pandoc globally. I don't know why the cabal sandbox has so much trouble with the network package.

**Comment by fspeech** [comment]
```cabal repl``` appears to run fine in the sandbox with the network package:
```
GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> import Network
Prelude Network> Network.withSocketsDo $ return ()
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package bytestring-0.10.4.0 ... linking ... done.
Loading package network-2.6.0.2 ... linking ... done.
```

**Comment by snoyberg** [comment]
Can you try rebuilding the network package from the command prompt and see if that resolves the issue?

**Comment by fspeech** [comment]
The network package was built from the command prompt. All the above were also from the command prompt.

**Comment by snoyberg** [comment]
I'm running a build on my Windows machine now to see if I can reproduce.

**Comment by snoyberg** [comment]
Sorry, I'm unable to reproduce any issues on my machine.

**Comment by fspeech** [comment]
I will try to debug more. I am guessing that my sandbox network package was now being built incorrectly, while my global network package was built correctly some days ago. I don't know what changed in the intervening days. It would be cool if you can give some clue on what may be indicated by the undefined references in the my opening post.

**Comment by DanBurton** [comment]
I was able to build `pandoc-1.13.2.1` on my Windows 8 machine with `minghc-7.8.4` using a stackage `lts-2.4` sandbox.

**Comment by ndmitchell** [comment]
On my laptop, with who knows what tools on the PATH (might be MinGHC 7.8, could quite easily have been something completely different...) I ran into a network issue on Friday, so it's possible I ran into a a problem here. Alternatively, I may have just had a totally borked system when I did my upgrade.

**Comment by snoyberg** [comment]
I just ran into this- or something related- with GHC 7.10.

**Comment by snoyberg** [comment]
I have a theory: there's a bug in the new version of the Cabal library (1.22) regarding custom build types and the autoconfUserHooks used by the network package, causing the cbits/initWinSock.c file to not be compiled in.

@ndmitchell @fspeech Can you confirm which version of the Cabal library is installed (`ghc-pkg list Cabal`)?

**Comment by ndmitchell** [comment]
I don't know - I have no real idea what was on the PATH. Note that if you have mismatched `cabal.exe` vs the package Cabal, then cabal install vs cabal build will use different Cabal versions (which is insanely confusing).

**Comment by snoyberg** [comment]
I still can't reproduce with GHC 7.8, but I can reliably with 7.10. I'm not sure if this is a GHC or Cabal bug yet. I'll do a little more investigation and then open an upstream issue.

**Comment by snoyberg** [comment]
Interesting, I've narrowed this down. In my case, having PortableGit's msys implementation in scope causes the breakage, presumably by confusing the autoconf script used by the network package. So yes, this *is* related to `PATH`.

**Comment by ndmitchell** [comment]
Any idea specifically which binary on the PATH makes it go wrong?

**Comment by snoyberg** [comment]
When I have PortableGit's msys on the PATH, then the configure script detects:

```
checking build system type... i686-pc-msys
checking host system type... i686-pc-msys
```

However, the configure.ac does a check for:

```
case "$host" in
*-mingw*)
        EXTRA_SRCS="cbits/initWinSock.c, cbits/winSockErr.c, cbits/asyncAccept.c"
        EXTRA_LIBS=ws2_32
        CALLCONV=stdcall ;;
```

I'm not sure why some versions of the msys toolchain report mingw and others msys. I'm going to play with tweaking the configure script to recognize msys as the same as mingw and see what happens.

**Comment by snoyberg** [comment]
Adding the following to the configure script does solve the problem:

```
*-msys*)
        EXTRA_SRCS="cbits/initWinSock.c, cbits/winSockErr.c, cbits/asyncAccept.c"
        EXTRA_LIBS=ws2_32
        CALLCONV=stdcall ;;
```

Sending a PR to network to make that change is trivial, but I'd like to understand why some systems report `i686-pc-msys` instead of the standard mingw stuff.

**Comment by snoyberg** [comment]
Wow, @luite sent almost an identical patch to what I was about to sent, back in December:

https://github.com/haskell/network/commit/2e40d5e8852b7303da658edf106dc21db3db4fc5

I'll go ask the maintainer to release this ASAP.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
