### ISSUE TITLE
Use GitHub releases section instead of README for download links

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#48]
It's impossible to tell which commit is the basis for the builds available in the README. Better would be to link to the "Releases" section and dynamically add new download links for each "release" as they are available. This way I can know that what I'm installing has or doesn't have certain changes.

**Comment by 3noch** [comment]
Another sweetness would be to embed the commit hash into the name of the installer so there's zero uncertainty. That *could* enforce a unique link for each release which would be far less stateful than the current method.

**Comment by snoyberg** [comment]
This sounds like a nice change. It will likely also make it easier for others (like @ndmitchell) to make releases, which I'm sure others will appreciate. I'll test it out today, I got some updated binaries from @DanBurton that I need to test.

**Comment by snoyberg** [comment]
I've created a first release at:

https://github.com/fpco/minghc/releases/tag/2015-05-14

Only one of the installers uploaded successfully for some reason, though I'm working on that.

**Comment by snoyberg** [comment]
OK, all the executables (and their GPG signatures) are up. Want to review?

**Comment by 3noch** [comment]
That looks awesome. I'm installing some now. How will this impact https://www.haskell.org/downloads/windows?

**Comment by 3noch** [comment]
FYI: This link seems useful: https://github.com/fpco/minghc/releases/latest

**Comment by snoyberg** [comment]
I'll talk to @chrisdone about getting a reasonable link onto haskell.org, possibly by having a redirect from somewhere else.

**Comment by 3noch** [comment]
So far the new builds seem to be working fine, and they include all the stackage commands.

**Comment by snoyberg** [comment]
I've updated the download links in the README, and sent a PR to haskell.org: https://github.com/haskell-infra/hl/pull/115

**Comment by 3noch** [comment]
Great work. Is this done then?

**Comment by snoyberg** [comment]
I think so. Thanks!
