### ISSUE TITLE
Native 7z support in NSIS

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#49]
If we used this NSIS plugin, we could make the installer much less noisy for unpacking 7z files.

http://nsis.sourceforge.net/Nsis7z_plug-in

**Comment by snoyberg** [comment]
We could make it much less noisy without the plugin, just by modifying the helper executable to hide the output. I thought having that information was a nice way of letting the user know that activity is happening.

**Comment by 3noch** [comment]
True, I thought of that as well. But I agree that knowing what's happening is nice, along with having a moving progress bar.

**Comment by ndmitchell** [comment]
Hmm, so do we pack 7z archives inside the installer now and unpack them at installation time on the users machine? Seems simpler if we unpacked the 7z files when building the installer, and relied on the standard installer 7z/pack compression to unpack them. Or am I misunderstanding, or is there a reason it is done that way?

**Comment by snoyberg** [comment]
It makes the generation of the installers much faster, and in my testing resulted in smaller executables too.

**Comment by ndmitchell** [comment]
Awesome - can't complain about that. You may also want to see if setting the installer as a whole to solid LZMA compression is still necessary - it might have no real size impact but improve the speed of installer creation.

**Comment by 3noch** [comment]
I forgot to mention that opening a terminal is more than noisy. Users can also accidentally "break" the install by clicking in the terminal which can cause it to pause until they hit "Enter". If they aren't aware of that, they might think the installer broke. Or, they can close the window prematurely.

**Comment by ndmitchell** [comment]
Consoles really suck, and are quite dangerous from a UI perspective. In the past, I've recompiled console apps to avoid spawning a console and run them that way, although in this case it sounds like the plugin is a better way to go. Happy to wrap any particular plugin you chose in the NSIS library if that helps (or feel free to send me a patch).

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
