### ISSUE TITLE
Loading package double-conversion-2.0.1.0: can't load .so/.DLL for: stdc++.dll

### ISSUE THREAD

**Issue by MaxDaten** [fpco/minghc#5]
Thx for minghc, was really looking forward to it.

I had two problems with `double-conversion` on windows with `haskell-platform` since my project depends on `text-format` and so on `double-conversion`.

the first problem happens when building the project or with this minimal example

```haskell
-- | Main.hs
module Main where
import Data.Double.Conversion.Text
import Data.Text.Internal
main = print $ showText (toShortest pi)
```
```
> cabal install double-conversion
> runhaskell.exe .\Main.hs
...
can't load .so/.DLL for: stdc++.dll (addDLL: could not load DLL)
```
related issue: bos/double-conversion#7

the second problem is similar 
```
> cabal get double-conversion
> cd double-conversion
> cabal sandbox init
> cabal install --dep
> cabal repl
...
Loading object (static) dist\build\cbits\hs-double-conversion.o ... ghc.exe: Unknown PEi386 section name `.gcc_except_table' (while processing: dist\build\cbits\hs-double-conversion.o)
ghc.exe: panic! (the 'impossible' happened)
  (GHC version 7.8.3 for i386-unknown-mingw32):
        loadObj "dist\\build\\cbits\\hs-double-conversion.o": failed
```
possible related: http://stackoverflow.com/a/13333029

I know, this is not `minghc` specific but I want to note that this problem still exists (and because I hoped a bit `minghc` could solve this for me;)). And maybe it makes someone aware of this problem again? This currently blocks me to use my project on the windows platform.

But is there a way to include this custom script from stackoverflow into this minghc, if it makes sense in general and is not to specific.

**Comment by ndmitchell** [comment]
I don't think @snoyberg or I are being much help here. Our best guess is it's a Cabal issue or a `double-conversion` issue, so I suggest you try one of their bug trackers.
