### ISSUE TITLE
Combined 32/64-bit installer

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#52]
It could be advantageous for some [like myself] to have a single installer for both architectures. This would allow for easily sharing the same install of MSYS, Git, and other ancillary tools (stackage-cli, etc.).

My particular use-case is not building `exe`s but shared `dll`s which have the inconvenient property that they can only be dynamically loaded by apps who have matching architecture. My app happens to run on the native architecture so I need `dll`s in both.

**Comment by ndmitchell** [comment]
I can see why this would be incredibly helpful at the GHC level (one set of libraries that were in sync and available in bit sizes), much like it is a pain that Cabal doesn't ensure profiling and vanilla libraries are consistent. I'm less convinced that running two installers is the bottleneck. Sharing the things like MSYS/Git/Stackage-cli should only really be saving disk space, which is basically free. Or is there some complexity I've missed that makes this more tricky than I am expecting?

**Comment by 3noch** [comment]
You're quite right that the GHC level would be drastically better. The only additional benefit of saved disk space is simplicity/consistency. With two installations it's possible (albeit unlikely) to have two different versions of GHC/Git/stackage-cli installed. I am paranoid of inconsistency, hence the idea for this enhancement. After working with the code for a bit, I'm pretty sure *making* an installer like this would be a cinch. But hosting it would be painful since we're already pushing the limits of what GitHub 
a cinch. But hosting it would be painful since we're already pushing the limits of GitHub's hosting generosity.

**Comment by ndmitchell** [comment]
An alternative would be having a "shared binaries" option in the installer, which puts the common files in a common place (e.g. `../MinGHC-Common`). That way you could get that consistency from multiple versions, e.g. GHC 7.8 and 7.10. I'm more of a fan of that, and you don't need any more hosting space.

**Comment by 3noch** [comment]
That's a great idea. But how would you have each installation point to the right versions of things in the common directory?

**Comment by 3noch** [comment]
Perhaps that would simple be the job of the switch scripts?

**Comment by ndmitchell** [comment]
Depends what we put in the common directory. For things like git/stackage/cabal/happy/alex, we probably always want the latest, even if you are using older versions.

**Comment by 3noch** [comment]
Should the installer ask for that common folder, like it does for the install folder?

**Comment by ndmitchell** [comment]
I guess, if it's not too much fuss. Although if it's an optional setting anyway, not such an issue (you could assume its a sibling).

**Comment by 3noch** [comment]
I might toy around with this. I'm not sure cabal should be common, since there seem to be a lot of issues with how cabal+GHC versions coordinate.

**Comment by 3noch** [comment]
Could MSYS be shared?

**Comment by ndmitchell** [comment]
Yes, I see no reason for MSYS not to be shared.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
