### ISSUE TITLE
Unhandled exception with GHC 7.10.1 (64-bit) installer

### ISSUE THREAD

**Issue by MetaMemoryT** [fpco/minghc#56]
```
The thread 0x2338 has exited with code 0 (0x0).
Unhandled exception at 0x00007FFF7084D85E (ntdll.dll) in cabal.exe: 0xC0000005: Access violation writing location 0x0000000000000024.
```

```
 Problem Event Name:	APPCRASH
  Application Name:	cabal.exe
  Application Version:	0.0.0.0
  Application Timestamp:	537f4b6c
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.17736
  Fault Module Timestamp:	550f4336
  Exception Code:	c0000005
  Exception Offset:	000000000003d85e
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	4105
  Additional Information 1:	eaf1
  Additional Information 2:	eaf1e5cf55d049b52cc336453c5217eb
  Additional Information 3:	a401
  Additional Information 4:	a4010aea529a8c4f5998b190a4559eff
```

**Comment by 3noch** [comment]
I've tried reproducing this, but everything is working fine for me. Can you tell us more about how you got here?

**Comment by MetaMemoryT** [comment]
ran installer, window popped up, I just closed the exception, the installer continued to run.  I am testing for defects in the install.

**Comment by 3noch** [comment]
@snoyberg @ndmitchell Could our install scripts be using an old `cabal` or `ghc` that's already on the PATH?

**Comment by MetaMemoryT** [comment]
That is definitely a possibility, I had a previous install.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. Stack neatly sidesteps previous install issues.
