### ISSUE TITLE
Getting strange linker warning when running cabal

### ISSUE THREAD

**Issue by MetaMemoryT** [fpco/minghc#57]
I opened this here: https://ghc.haskell.org/trac/ghc/ticket/10454#comment:1

in case its not minghc specific.

```
ghc.exe: warning: _tzset from msvcrt is linked instead of __imp__tzset
ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
ghc.exe: warning: WSAStartup from ws2_32 is linked instead of __imp_WSAStartup
ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
ghc.exe: warning: accept from ws2_32 is linked instead of __imp_accept
ghc.exe: warning: inet_ntoa from ws2_32 is linked instead of __imp_inet_ntoa
ghc.exe: warning: getnameinfo from ws2_32 is linked instead of __imp_getnameinfo
ghc.exe: warning: getaddrinfo from ws2_32 is linked instead of __imp_getaddrinfo
ghc.exe: warning: freeaddrinfo from ws2_32 is linked instead of __imp_freeaddrinfo
ghc.exe: warning: LeaveCriticalSection from kernel32 is linked instead of __imp_LeaveCriticalSection
ghc.exe: warning: EnterCriticalSection from kernel32 is linked instead of __imp_EnterCriticalSection
ghc.exe: warning: DeleteCriticalSection from kernel32 is linked instead of __imp_DeleteCriticalSection
ghc.exe: warning: DeleteCriticalSection from kernel32 is linked instead of __imp_DeleteCriticalSection
ghc.exe: warning: InitializeCriticalSection from kernel32 is linked instead of __imp_InitializeCriticalSection
ghc.exe: warning: InitializeCriticalSection from kernel32 is linked instead of __imp_InitializeCriticalSection
```

**Comment by 3noch** [comment]
Is there a quick example of what you're building with this? I've seen this in `ghci` but I don't recall seeing it from GHC directly. That might because I use `cabal` for everything usually. You must be building a raw file then.

**Comment by MetaMemoryT** [comment]
I am running `cabal test` on https://github.com/prowdsponsor/esqueleto

a hello world compiled with ghc directly does not create the linking warnings.

**Comment by 3noch** [comment]
You might want to change your GHC trac ticket to say that, since "anything" would include a "hello world" program, but that's not causing any issues.

**Comment by MetaMemoryT** [comment]
updated, guess I got to narrow it down some more, how could I isolate this problem more?

**Comment by MetaMemoryT** [comment]
I did a `cabal init` and  `cabal install` ,  the most simplest package did not reproduce the warning messages.

**Comment by 3noch** [comment]
Not sure about the critical sections, but I'll bet many of those come from building `network`. You could try building `network` by itself.

**Comment by 3noch** [comment]
For the GHC ticket, you might also want to add what version of Windows you're using and what architecture.

**Comment by 3noch** [comment]
See this: https://ghc.haskell.org/trac/ghc/ticket/8918

**Comment by 3noch** [comment]
Looks like later versions of `network` have fixed this. So it could be that your dependencies rely on an old version of `network` or there is some other library working with MSYS2 to get it's socket handling.

**Comment by Xe** [comment]
I just ran into this with a "hello world" program.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
