### ISSUE TITLE
Stackage sandbox broken by server

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#58]
@snoyberg @DanBurton Major problem: `stackage sandbox init` was broken for [probably] all snapshots. `stackage sandbox` looks for the string `"-- Stackage snapshot from: http://www.stackage.org/snapshot/"` in `cabal.config` but the server now gives a URL without the `snapshot/` path. We can't fix this in `stackage sandbox` alone because countless people already have the current version installed, as we package it with MinGHC. I filed the bug here: https://github.com/fpco/stackage-sandbox/issues/4

**Comment by snoyberg** [comment]
Sorry for the breakage here. It should be fixed now.

**Comment by 3noch** [comment]
Thanks for getting on it so quickly! It seems to be fixed. Shall we start building an auto-upgrading system for stackage CLI tools? :wink:

**Comment by snoyberg** [comment]
Well, yes, sort of. A few of us have been collaborating on a project which will likely subsume the stackage CLI tools so far. It's going to go public next week, but I'll send you an invite so you can see what I'm talking about now.

**Comment by 3noch** [comment]
@snoyberg I can't wait. I think what you're building is what I've been wanting for a long time. :D
