### ISSUE TITLE
Uninstall blindly removes everything, recursing even through junctions

### ISSUE THREAD

**Issue by tejon** [fpco/minghc#62]
First, the horror story: for convenience, I had `msys-1.0.1\home\tejon` linked to my data drive, `D:\`. Note that Windows only permits "junctions" (soft links) of directories; in Explorer this is represented with a different icon from other folders, and it can be moved or deleted/recycled without affecting the link target. You can probably guess the story: I started the MinGHC uninstall, and a few minutes later there was a moment of panic when I checked progress and saw what files were being deleted! Luckily it hit my massive last-four-harddrives backup folder first, so nothing I've touched in at least a year was affected; and more luckily, Recuva hasn't thrown a single error yet while undeleting.

This in and of itself is a pretty huge issue (though it might be intrinsic to NSIS), but it made me think about some previous MinGHC un/reinstalls and the fact that when I use MinGW to build something, I generally `make install` and everything goes right where it should in the MSYS hierarchy. Is it necessary that I have to delete and rebuild it all, to get a clean MinGHC install? A lot of installers remember what they put there, and don't remove anything they didn't.

Granted this all started because I've put off updating for a while due to a project in progress; I don't know if the new Git dependency obviates the whole topic.

**Comment by 3noch** [comment]
I'm curious how you got a symlink to your own stuff in the MinGHC folders?

**Comment by tejon** [comment]
[`mklink`](https://technet.microsoft.com/en-us/library/cc753194.aspx)

**Comment by 3noch** [comment]
Sorry, the meat of my question was *in the MinGHC folders*. How did you get symlinks to your files inside folders managed by MinGHC?

**Comment by tejon** [comment]
Oh, what MSYS maps to `/` is just its own folder. If you open its shell and dig through /c/ you'll find it duplicated there, too. The only management it does is mapping that to `/` and mapping `?:` to `/?/`, it's not a sandbox or anything.

**Comment by ndmitchell** [comment]
Eek. I guess it would be a good idea to remove the uninstaller until we've figured out how to solve that. Not sure if there are any good MSYS ways of doing that, or even any good Windows ways in general.

**Comment by 3noch** [comment]
Forgive my ignorance, but I don't understand yet. I have uninstalled countless times without problems. Can you give me steps to reproduce this?

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
