### ISSUE TITLE
Consider embracing full MSYS2

### ISSUE THREAD

**Issue by tejon** [fpco/minghc#63]
After finally upgrading to the Git-powered version of MinGHC, I was disappointed to find that it doesn't include the one thing I was really looking forward to from MSYS2: `pacman`. Since I was already in a transition state, I decided to grab MSYS2 directly and see how much effort it would be to get everything up and running. My verdict is best summarized as "holy crap, guys."

* The 64-bit version includes the 32-bit MinGW, which looks like a big step toward #52.

* `git` is available as a `pacman` package.

* So are `sdl`/`sdl2`, `gtk`, `glut`, `pkg-config`... everything in #25, [and then some](http://sourceforge.net/p/msys2/wiki/Packages/).

* In its shells, its own paths are prepended. Outside, they don't exist. Relevant to #53 and #18.

***
That's not to say there are no downsides at all. Potential complications I noticed:

* The [installer](https://msys2.github.io/) provides only a minimum context for running `pacman`. Even after following the instructions behind that link, it doesn't include the `gcc` toolchain. Fetching it would have to be scripted.

* ~~The `pacman`-fetched `git` is not available at a regular Windows prompt. If we don't want to require use of `bash` for `stackage`, it'll still be necessary to install regular GitForWindows. However, there would be no reason to expose the existence of GitBash; MSYS2 encompasses and supercedes that.~~

* ~~MSYS and MinGW have separate shells (plus a third for 32-bit with the 64-bit installation). MinGW is for stuff that requires the GNU toolchain; MSYS is for stuff that requires a full POSIX subsystem, and it's recommended to avoid this unless absolutely necessary because there's a cost for that emulation layer. Very little in the Haskell ecosystem requires the latter -- `network` does fine with just MinGW -- but some might... and sadly, `pacman` does. So I think both shells would need to be exposed, which means explaining the difference to the user.~~

**Edit:** Looks like using a path-switching command file (as MinGHC currently does), or if you're lazy like me just appending `msys64\usr\bin` and `msys64\mingw64\bin` to path, lets you stick with a standard Windows shell for pretty much everything but `pacman`. Cabal can find `sh`, there's no need for an additional Git4Win installation, `pkg-config` even works correctly for libraries installed via `pacman`.

**Comment by snoyberg** [comment]
I'm OK in principle with this change. Is there a non-installer version of msys2 that could be used? It would be a bit trickier to call another installer from within minghc.exe.

**Comment by 3noch** [comment]
My rather ininformed and unimportant opinion is that MinGHC has "min" in the name for a reason. If someone wants all of MSYS2, all they need to do is install GHC by itself along with MSYS2. It's actually quite easy. I don't see a reason to significantly complicate MinGHC to pull this off. I think a full MSYS2 install would not help the common case: installing the network library in a raw Windows shell. IIRC that was a primary motivator for this project as opposed to Haskell Platform. I thought including Git was a stretch but I am a fan of Stackage so I can cope... ;)

**Comment by tejon** [comment]
>  I think a full MSYS2 install would not help the common case: installing the network library in a raw Windows shell.

Eh? I'm actually on MSYS+GHC right now so I can't directly test this, but I never thought that was a goal and I'm pretty sure it's impossible. The reason you can't install `network` from a Windows shell is that it needs to invoke a `sh`-based script. The rest of the GNU toolchain is also involved, of course, but it's the `./configure` invocation that makes it necessary to do more than put appropriate tools on the path.

**Comment by ndmitchell** [comment]
Installing the network library in a standard windows shell has always been the goal, and it works (or at least does with the slightly older MinGHC I've got installed).

**Comment by tejon** [comment]
Huh! I've been using MinGHC from close to the beginning, and I've always just launched the MSYS shell for installs. How does it run the script?

**Comment by ndmitchell** [comment]
You can call sh from the standard windows command prompt, and it runs an sh-logic shell under the windows command prompt UI. I think Cabal calling sh does this all automatically, nothing difficult.

**Comment by tejon** [comment]
Ahh, so Cabal does the dirty work if `sh` is on the path. Fair enough, and that explains why I didn't find a GitBash icon supplied with the most recent install. :)

Still, @3noch, I think it's also good to provide a streamlined, no-fuss install with as much power as possible as long as that power doesn't get in the way when it's not needed. MSYS2 won't interfere with the `CMD.EXE` workflow any more or less than MSYS1 or GitBash did.

**Comment by asampal** [comment]
I was just going to add an issue to ask if it would be possible to have a variant of MinGHC for users already using MSYS2. Found this issue which is close wrt the goal I was after. I would second the request for fully embracing MSYS2 - after fiddling around with Cygwin and various other msys/mingw distributions over the years, I have to say that MSYS2 really stands out.

**Comment by tejon** [comment]
Looks like using a path-switching command file (as MinGHC currently does), or if you're lazy like me just appending `msys64\usr\bin` and `msys64\mingw64\bin` to path, lets you stick with a standard Windows shell for pretty much everything but `pacman`. Cabal can find `sh`, there's no need for an additional Git4Win installation, `pkg-config` even works correctly for libraries installed via `pacman`. This basically means the only hurdle is automating the initial package fetches.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. I think Stack is fully MSYS2.
