### ISSUE TITLE
Virus alert on installation

### ISSUE THREAD

**Issue by alexbiehl** [fpco/minghc#64]
Hey, 

I tried installing minghc on two separate win7 Machines, both times avira antivir pops up complaining about dropper/gen trojan. I can not provide additional Information on which file it happened since Corporate policy locks the Computer up on Security alerts. 

Is that a known problem? I will try to gain additional Information later.

(on my phone)

**Comment by 3noch** [comment]
I've never heard of that before...

**Comment by tejon** [comment]
It looks like "dropper/gen" is a category invented by Avast (and I guess picked up by Avira) for trojans whose only behavior is to download other malware behind your back. The "gen" is for generic -- this is heuristic analysis, not a targeted signature, so basically it's just looking for programs that might download things independently of the installer. Could definitely be triggering on Cabal or Git, especially coming from what I'm sure is an unrecognized installer. Nothing much to do but report the false positive.

**Comment by alexbiehl** [comment]
My company sent the suspicous file (createsymlink or something) to Avira support and they registered it as false positives. Should be fixed in the next few updates. So great news!

**Comment by snoyberg** [comment]
Great, thank you!

**Comment by ndmitchell** [comment]
Seems like this was fixed, and may even have helped Stack.
