### ISSUE TITLE
Cabal not working windows vista

### ISSUE THREAD

**Issue by xpika** [fpco/minghc#66]
OS - vista

cabal install hell
Config file path source is default config file.
Config file C:\Users\Administrator\AppData\Roaming\cabal\config not found.
Writing default configuration to
C:\Users\Administrator\AppData\Roaming\cabal\config
realgcc.exe: CreateProcess: No such file or directory

**Comment by 3noch** [comment]
Can you paste your `PATH`?

**Comment by snoyberg** [comment]
No response, closing.
