### ISSUE TITLE
Installing as non-admin is difficult

### ISSUE THREAD

**Issue by ndmitchell** [fpco/minghc#67]
Installing as non-admin was tricky since it automatically requests admin privileges. The only way I could figure was setting the environment variable `__COMPAT_LAYER=RUNASINVOKER` before running the binary. Is there any easier way? Can we stop requiring admin as default and make users right click and "Run as admin", which is far easier than the reverse?

**Comment by snoyberg** [comment]
I think we can do that. In fact, I really consider it an error on my part that I *didn't* do that when I switched it to a local installation directory. What change needs to be made?

**Comment by ndmitchell** [comment]
http://superuser.com/a/103012/240196 describes the heuristics that make it admin - they are pretty whacky. It probably needs a manifest to override that: https://msdn.microsoft.com/en-us/library/bb756929.aspx

**Comment by 3noch** [comment]
See also http://nsis.sourceforge.net/Reference/RequestExecutionLevel

**Comment by 3noch** [comment]
@ndmitchell Would [`requestExecutionLevel`](http://hackage.haskell.org/package/nsis-0.2.5/docs/Development-NSIS.html#v:requestExecutionLevel) not do the trick?

**Comment by ndmitchell** [comment]
@3noch I don't know - certainly worth a try (depends if NSIS translates that setting into a manifest - it may well do).

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
