### ISSUE TITLE
Repackage MinGHC 7.10 with latest cabal

### ISSUE THREAD

**Issue by solatis** [fpco/minghc#69]
Latest cabal `1.22.6.0` fixes haskell/cabal#2502 , which is kind of a big deal on Windows. MinGHC 7.10.2 should use this version of cabal.

**Comment by snoyberg** [comment]
Kicking off a build now, I agree that that's important. @3noch do you want to do the release on this?

**Comment by snoyberg** [comment]
Sorry, should have clarified: I'm building cabal-install right now.

**Comment by 3noch** [comment]
I'll give it a try.

**Comment by snoyberg** [comment]
Cool, let me know if you want some help. I've just pushed a new commit that bumps the cabal.exe inside cabal.7z, so it should just be a matter of rerunning the build.

**Comment by 3noch** [comment]
Sweet!

**Comment by 3noch** [comment]
@snoyberg I'm assuming this will work fine with all 4 GHC versions we support?

**Comment by snoyberg** [comment]
It should. If it doesn't, it's a serious regression in cabal-install (which is possible, but hopefully unlikely).
