### ISSUE TITLE
Register the uninstaller with Windows

### ISSUE THREAD

**Issue by ndmitchell** [fpco/minghc#7]
From #6: minghc didn't register itself in Windows' "Add or remove programs", so I had to run uninstall.exe by hand.

Needs adding there, and removing from there on uninstall. Annoying, but not too hard.

**Comment by elieux** [comment]
A little note:

> Maybe the uninstaller should also pop up under the start menu, as just an uninstall entry? Seems a bit weird, but most users probably expect it.

This trend is largely abandoned now. Especially with the search-as-you-type feature, putting such links in Start seems counter-productive.

**Comment by 3noch** [comment]
Let's not forget this key feature!

**Comment by 3noch** [comment]
I should mention that the new location of the install makes this even more important than before: it's a lot harder to find the uninstaller!

**Comment by ndmitchell** [comment]
It's not forgotten, but with the current stuff on my plate, I'm unlikely to get at this for a few months. Pull requests very welcome!

**Comment by 3noch** [comment]
@ndmitchell Any ideas how to do it? If you give me a direction I might be able to pull it off.

**Comment by ndmitchell** [comment]
@3noch I suggest you follow the code in #50, since that seems very well done :). I've never actually done it myself before, but that's what I'll copy next time I need to.
