### ISSUE TITLE
7.8.4/32 installer: "string limit exceeded"

### ISSUE THREAD

**Issue by eflister** [fpco/minghc#71]
```
Output folder: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386
Created uninstaller: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\uninstall.exe
Extract: ghc-7.8.4-i386.tar.xz
Extract: git-2.4.0.1.7z... 100%
Output folder: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin
Extract: 7z.dll... 100%
Extract: 7z.exe... 100%
Extract: alex.7z
Extract: cabal.7z
Extract: happy.7z
Extract: minghc-post-install.exe.7z
Extract: stackage-cli.7z
Output folder: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386
Execute: "C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\7z.exe" x -y "-oC:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin" "C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\minghc-post-install.exe.7z"
Delete file: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\minghc-post-install.exe.7z
Execute: "C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\minghc-post-install.exe" "ghc-7.8.4-i386.tar.xz" "git-2.4.0.1.7z"
Delete file: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\bin\minghc-post-install.exe
Create folder: C:\Users\nlab\AppData\Local\Programs\minghc-7.8.4-i386\switch
String limit exceeded
```

**Comment by snoyberg** [comment]
@ndmitchell Is this an issue with using an unpatched NSIS for making the installers?

**Comment by ndmitchell** [comment]
Yep, the PATH exceeds the string limit. The Haskell NSIS library checks the limit rather than just corrupting the PATH. (As the standard NSIS does). How easy would it be to find a patched NSIS?

**Comment by eflister** [comment]
meanwhile, could the error be changed to specify that the PATH is the issue?

**Comment by snoyberg** [comment]
This is the one I've used previously, I don't know if it has the patch for longer PATHs. @ndmitchell Could you check? I'm not sure how to go about that.

**Comment by 3noch** [comment]
I'm guessing I built this installer. I didn't know I needed to patch NSIS. Terribly sorry. I've been using version 3.0b1 if that makes a difference.

**Comment by snoyberg** [comment]
I don't think this is coming from the nsis you're using, but from the
library.

**Comment by ndmitchell** [comment]
The error comes from the Haskell library, but it's detecting an error in the underlying NSIS binary. I've just released 0.3 of the `nsis` package which improves the error on an excessively long PATH (it aborts with nicer errors and more detail), plus documents the [`strCheck` function](http://hackage.haskell.org/package/nsis-0.3/docs/Development-NSIS.html#v:strCheck) as:

> NSIS (the underlying installer, not this library) uses fixed length string buffers, defaulting to 1024 bytes. Any strings longer than the limit may cause truncation or segfaults. You can get builds supporting longer strings from http://nsis.sourceforge.net/Special_Builds.

**Comment by ndmitchell** [comment]
@3noch I suggest you grab the "Large strings" build from http://nsis.sourceforge.net/Special_Builds and rebuild with that. But even if you don't, with the new `nsis` library, we should get more informative errors. To be honest, I'm somewhat surprised that @eflister is the first user to hit this, I was expecting it to happen to more people.

**Comment by 3noch** [comment]
I'll give it a try soon.

**Comment by 3noch** [comment]
Looks like "soon" means mid-next week. Sorry for the delay. Feel free to jump on it if you have time.

**Comment by ndmitchell** [comment]
I'm off all weekend so won't have time to do anything, plus its not clear I still know how :).

@eflister - as a workaround select it not to modify your PATH, and then add C:\...\MinGHC\switch to the PATH by hand, then you can use minghc.bat to put the tools on your PATH. Alternatively, clean up your PATH variable (>1Kb is often a sign its got dead stuff on it) and run again.

**Comment by eflister** [comment]
my path is 1467 characters long, and fully 60% of it is from 2 installs of minghc 7.10.1 (32 and 64).  i wanted 64, but had to give up cuz it couldn't install `hs-bibutils` (see https://stackoverflow.com/questions/30929551/which-unix-compatibility-toolchain-to-use-with-cabal-install-on-windows).  i wrote to the maintainer (andrea.rossato@unitn.it) but never heard back.  similar reports:
https://github.com/snoyberg/yaml/issues/44
https://ghc.haskell.org/trac/ghc/ticket/9215
https://github.com/bsl/bindings-GLFW/pull/28/files

do you guys recognize this problem?

anyway, the 32 bit minghc worked, after dealing with  github.com/haskell/cabal/issues/2502 / github.com/haskell/cabal/issues/2525 and giving up on my dreams of updating cabal-install.  i don't need 7.8.4, anymore, that was only to see if it would let me update cabal-install.

of course, the latest `HaXml` wouldn't install (looks like a windows vs unix whitespace problem), trial and error found an older version would.  i wrote to malcolm (the maintainer) and haven't heard back.

so i have it limping along...  painful!

**Comment by ndmitchell** [comment]
Sorry it's been such an uphill struggle!

* We'll get the PATH thing fixed, we know how to do it, we'll improve the error and fix that one for you, at least. Sorry we mostly caused the PATH thing in the first place :).
* I don't recommend 64bit Windows because its less tested, and you rarely want to be one of the first. Other people have reported success, but obviously not on everything.
* Doing stuff with cabal-install is a bit of a pain. There's a new project [Stack](https://github.com/commercialhaskell/stack) designed to fix a lot of these issues which has considerable overlap with the MinGHC team. We've also got a newer cabal-install in the latest MinGHC, which should help.
* I'm talking to Malcolm about your HaXml issues and trying to get that fixed (we work together).
