### ISSUE TITLE
Support no gmp builds

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#72]
We need this badly. [More discussion](https://github.com/commercialhaskell/stack/issues/399)

**Comment by 3noch** [comment]
I can upload these if you guys think it would be valuable. I have GHC builds for 7.8.4, 7.10.1, and 7.10.2, so all I'd need to do is hijack the installer script to pack up my custom builds instead of using the downloaded ones.

**Comment by snoyberg** [comment]
I don't see a downside to that.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. Not sure what Stack does about these.
