### ISSUE TITLE
Cannot install networks 2.6.2.1 on Windows 64 bits with 32 bits installer

### ISSUE THREAD

**Issue by KeesBleijenberg** [fpco/minghc#74]
I've installed the windows minimal GHC installer 32 bits on Windows 7 64 bits from http://neilmitchell.blogspot.nl/2014/12/beta-testing-windows-minimal-ghc.html.
No errors during installation. When I type in ghc --version I still get the previous version. I deinstalled the old version, removed all packages and reboot.
Now I get ghc ver 7.10.1. ghc-pkg list shows only a few packages. Everything seems ok.

Then I want to install htpp (which should install network) I get the following erros (see below).
What is wrong?

Greetings,
Kees

Resolving dependencies...
Configuring network-2.6.2.1...
Failed to install network-2.6.2.1
Build log ( C:\Users\kees\AppData\Roaming\cabal\logs\network-2.6.2.1.log ):
Configuring network-2.6.2.1...
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
checking build system type... i686-pc-msys
checking host system type... i686-pc-msys
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for unistd.h... (cached) yes
checking winsock2.h usability... yes
checking winsock2.h presence... yes
checking for winsock2.h... yes
checking ws2tcpip.h usability... yes
checking ws2tcpip.h presence... yes
checking for ws2tcpip.h... yes
checking arpa/inet.h usability... no
checking arpa/inet.h presence... no
checking for arpa/inet.h... no
checking netdb.h usability... no
checking netdb.h presence... no
checking for netdb.h... no
checking netinet/in.h usability... no
checking netinet/in.h presence... no
checking for netinet/in.h... no
checking netinet/tcp.h usability... no
checking netinet/tcp.h presence... no
checking for netinet/tcp.h... no
checking sys/socket.h usability... no
checking sys/socket.h presence... no
checking for sys/socket.h... no
checking sys/uio.h usability... no
checking sys/uio.h presence... no
checking for sys/uio.h... no
checking sys/un.h usability... no
checking sys/un.h presence... no
checking for sys/un.h... no
checking linux/can.h usability... no
checking linux/can.h presence... no
checking for linux/can.h... no
checking linux/tcp.h usability... no
checking linux/tcp.h presence... no
checking for linux/tcp.h... no
checking net/if.h usability... no
checking net/if.h presence... no
checking for net/if.h... no
checking for readlink... no
checking for symlink... no
checking for if_nametoindex... no
checking for struct msghdr.msg_control... no
checking for struct msghdr.msg_accrights... no
checking for struct sockaddr.sa_len... no
checking for in_addr_t in netinet/in.h... no
checking for SO_PEERCRED and struct ucred in sys/socket.h... no
checking for getpeereid in unistd.h... checking for getpeereid... no
checking for _head_libws2_32_a in -lws2_32... yes
checking for getaddrinfo... no
checking for getaddrinfo if WINVER is 0x0501... yes
checking for gai_strerror... no
checking whether AI_ADDRCONFIG is declared... no
checking whether AI_ALL is declared... no
checking whether AI_NUMERICSERV is declared... no
checking whether AI_V4MAPPED is declared... no
checking whether IPV6_V6ONLY is declared... yes
checking whether IPPROTO_IP is declared... yes
checking whether IPPROTO_TCP is declared... yes
checking whether IPPROTO_IPV6 is declared... yes
checking for sendfile in sys/sendfile.h... no
checking for sendfile in sys/socket.h... no
checking for gethostent... no
checking for accept4... no
configure: creating ./config.status
./configure: line 4876: test: too many arguments
./configure: line 4876: test: too many arguments
./configure: line 4876: test: too many arguments
./configure: line 4876: test: too many arguments
./configure: line 4876: test: too many arguments
./configure: line 4876: test: too many arguments
configure: error: could not make ./config.status
cabal: Error: some packages failed to install:
HTTP-4000.2.20 depends on network-2.6.2.1 which failed to install.
network-2.6.2.1 failed during the configure step. The exception was:
ExitFailure 1

**Comment by KeesBleijenberg** [comment]
Additional I tried this

- cabal install network (instead of cabal install http). No difference.
- cabal install network as administrator. No difference.
- cabal unpack network
  cd  network-2.6.2.1
  cabal configure
  in a editor I opend configure. At line 4876 ...
  if test $ac_delim_n = $ac_delim_num; then
    break
  elif $ac_last_try; then
    as_fn_error $? "could not make $CONFIG_STATUS" "$LINENO" 5
  else ....
  
  This seems bash to me. I can't see an error (I know almost nothing about bash)

Kees

**Comment by KeesBleijenberg** [comment]
You can see my configure file at:
http://www.tbsoftware.nl/configureNetwork/configure

Kees

**Comment by KeesBleijenberg** [comment]
In configure I've added the line 
echo $ac_delim_n
The extra line it prints was: 62 lines match

I've added this line:
....
echo $ac_subst_vars
ac_delim_num=`echo "$ac_subst_vars" | grep -c '^'`
....
This was the output:
LTLIBOBJS LIBOBJS EXTRA_SRCS EXTRA_LIBS EXTRA_CPPFLAGS CALLCONV EGREP GREP CPP OBJEXT EXEEXT ac_ct_CC CPPFLAGS LDFLAGS CFLAGS CC host_os host_vendor host_cpu host build_os build_vendor build_cpu build target_alias host_alias build_alias LIBS ECHO_T ECHO_N ECHO_C DEFS mandir localedir libdir psdir pdfdir dvidir htmldir infodir docdir oldincludedir includedir localstatedir sharedstatedir sysconfdir datadir datarootdir libexecdir sbindir bindir program_transform_name prefix exec_prefix PACKAGE_URL PACKAGE_BUGREPORT PACKAGE_STRING PACKAGE_VERSION PACKAGE_TARNAME PACKAGE_NAME PATH_SEPARATOR SHELL
This line contains 62 words. 
It looks like this script exceeds the limits of 'test'.

**Comment by KeesBleijenberg** [comment]
I've found the solution. 
Cabal uses the wrong grep. The grep it uses was from Delphi (which came earlier in the path)

**Comment by 3noch** [comment]
Glad you found it. I figured it was something wrong with the `PATH` ordering. @ndmitchell @snoyberg Would it make sense to add a sanity check after install to see if there are other tools shadowing MinGHC's? I'm not sure of another way to fix this generally.

**Comment by snoyberg** [comment]
It would be very difficult to guess all of the tools that need to be available _and_ determine that the version the user has is different than the one we need. We may want to start a real conversation about the interaction between MinGHC and stack here; stack solves this problem by modifying the PATH at the time of calling external tools to force its version of msys to take precedence. We can't do that with cabal.

Or perhaps we need to tell users with stack that they must use the switcher script to ensure things work perfectly.

**Comment by 3noch** [comment]
I had the exact same thoughts. :)

**Comment by 3noch** [comment]
`stack` is a much better experience for Windows because it controls GHC installations and `PATH` messiness internally.

**Comment by snoyberg** [comment]
Perhaps this should be a separate issue, but I'll dive in here anyway...

I clearly consider MinGHC+cabal-install an inferior solution (as I am biased), since I think stack > cabal-install. The question then becomes: what does MinGHC offer over plain stack? As I see it:

* Easier installation procedure
* Includes the big downloads (GHC and msys) in the initial download, which is very useful if you're going to install the toolchain on multiple systems

The advantage of downloading plain stack is:

* Quicker initial install
* Doesn't require any registry changes
* Will grab the best version of GHC for you, instead of whatever one happens to be available

Those are my thoughts, what does everyone else think?
