### ISSUE TITLE
ghc 7.10.2

### ISSUE THREAD

**Issue by ka3a4ok** [fpco/minghc#78]
Is there any plan for minghc with ghc 7.10.2?

**Comment by snoyberg** [comment]
I'm uploading right now, thanks for the reminder

**Comment by snoyberg** [comment]
Could you test out https://github.com/fpco/minghc/releases/edit/untagged-c987d09a798ab9f1d8aa before we publish it? Pinging @3noch

**Comment by 3noch** [comment]
Sweet! Thanks for doing this. Did you happen to use the patch for the max-string-length `PATH` error?

**Comment by 3noch** [comment]
I noticed you didn't make any code changes, shall we just upload these to the existing release?

**Comment by snoyberg** [comment]
No, I don't think so. Let's make sure to get that into the next set of releases. I'm going to push some commits now that add in the stack binary.

**Comment by snoyberg** [comment]
I'm OK with moving it to an existing release instead, no preference from me.
