### ISSUE TITLE
Installer with 64-bit GHC should contain 64-bit Stack executable

### ISSUE THREAD

**Issue by rkarp** [fpco/minghc#82]
As of now, the 64-bit installer contains the 32-bit `stack.exe`. If you create a new Stack configuration with `stack init` and then try to build it, Stack will tell you that it expects 32-bit GHC, which cannot be found. To build your project you have to call Stack with `--arch x86_64` every time or add the setting to your `stack.yaml` manually.

This is because Stack always tries to use the same GHC architecture it was built with itself by default.

**Comment by snoyberg** [comment]
I'm testing a fix for this now

**Comment by snoyberg** [comment]
Can you test out the installers at:

https://github.com/fpco/minghc/releases/edit/untagged-b886736e205f1ac220b5

Pinging @3noch

**Comment by rkarp** [comment]
The link doesn't lead to anything for me.

**Comment by snoyberg** [comment]
Alright, try this please: https://github.com/fpco/minghc/releases/tag/2015-08-13

**Comment by 3noch** [comment]
@snoyberg Did you use the patched version of NSIS?

**Comment by snoyberg** [comment]
I don't know, I presume the non-patched. Where can I download the patched version from?

**Comment by 3noch** [comment]
@snoyberg I can upload builds if you want, or you can follow the newly improved README instructions which describe how to do that.

**Comment by snoyberg** [comment]
It's the end of the day for me right now, so I'm about to turn in. If you don't mind uploading these round, I'd appreciate it :)

**Comment by 3noch** [comment]
Sure.

**Comment by rkarp** [comment]
I've tested it, it works correctly for both new 64 bit installers.

**Comment by 3noch** [comment]
@rkarp Excellent. Thank you. I'm working on creating more "official" release builds. Those should be out by the end of the day.
