### ISSUE TITLE
"stack haddock" fails when using system GHC

### ISSUE THREAD

**Issue by arotenberg** [fpco/minghc#85]
See [this StackOverflow question](http://stackoverflow.com/q/32416942/925960). In short, the following fails with an error about base not being in the build plan on a fresh 64-bit Windows 7/8 MinGHC 2015-08-13 installation:

> stack new stack-test new-template
> cd stack-test
> stack haddock

Changing "stack haddock" to "stack haddock --install-ghc --no-system-ghc" makes it work.

**Comment by snoyberg** [comment]
I just tested, and I'm unable to reproduce the problem. Can you capture the full output of the following commands and put them in a paste:

```
stack path
stack exec which ghc
stack haddock --verbose
ghc-pkg describe base --expand-pkgroot
stack exec -- ghc-pkg describe base --expand-pkgroot
```

**Comment by arotenberg** [comment]
Interesting, it only happens when I install MinGHC in a directory in C:\Program Files. If I let the installer use the default install location in AppData\Local\Programs, the issue doesn't occur. However, if I install in Program Files, the issue occurs even if I run the commands with admin privileges.

Output from the commands you listed: https://gist.github.com/arotenberg/030e00254737a98496b5

**Comment by snoyberg** [comment]
That certainly narrows it down, sounds like a bug in stack's Haddock code not knowing how to handle quoted filepaths. We'll get that fixed for the next release (pinging @borsboom), but it looks like you at least have a decent workaround until then.

**Comment by snoyberg** [comment]
OK, I've pushed a commit to stack that addresses this problem. If you build from master, stack should work with your install of MinGHC.
