### ISSUE TITLE
Provide a code-signed installer .exe

### ISSUE THREAD

**Issue by sinelaw** [fpco/minghc#88]
Current installer is not signed and when installing a security warning is shown.

**Comment by ndmitchell** [comment]
Do FP Complete have a certificate they could sign these things with? Even if they do, is it suitable to use on MinGHC?

**Comment by snoyberg** [comment]
Can someone point me to information on how to sign installers for windows?
I've never done it before, and I don't know what kind of certificate we
need.

**Comment by 3noch** [comment]
See #61

**Comment by sinelaw** [comment]
I've done it in the past using code signing certificates from GoDaddy (a
few hundred dollars IIRC)

https://www.godaddy.com/help/signing-windows-code-with-microsoft-signtool-4778
