### ISSUE TITLE
could minghc-compiled exe's crash win7/64?

### ISSUE THREAD

**Issue by eflister** [fpco/minghc#89]
i use `minghc` (could only get 32-bit to work even though this is 64-bit OS) to compile `BlogLiterately`, which i call from a large matlab program.  `BlogLiterately` required me to manually install `Win32OpenSSL`.  ever since adding this, in about 20% of runs, the entire machine black-screens mid-execution, and needs to be rebooted.  the matlab log does not implicate this call, but i can't be sure that it has completely flushed from the OS buffer to disk at the time of the crash.  it feels like a shutdown due to bad RAM or overheating, but i have memtest86'd and recorded/analyzed temperature logs, which aren't showing problems.  the windows events logs don't show anything except for the reboots from unexpected shutdowns.  so i am grasping at straws, and nothing changed except my adding `minghc`/`BlogLiterately` to the machine, and the crash only occurs when running this job.  do you guys think they could be responsible?  any tips on further debugging this?

**Comment by snoyberg** [comment]
If that's what's happening, it would be a GHC behavior, not MinGHC. And regardless of what an executable is doing- unless it's running in kernel space- it shouldn't result in a system crash. I think that's almost certainly a Windows bug - or at least a driver bug - or a hardware problem. It's entirely possible that the Haskell executable is somehow triggering that.

**Comment by eflister** [comment]
ok thanks for the response -- if you can offer any suggestions about what i could do to try to track it down, i'm out of ideas...  i can add log output to the matlab code, but need to figure out some way to assure there is no buffering for that to be worth it -- you don't happen to know of a way to force windows to flush all disk writes, do you?  :)

**Comment by eflister** [comment]
hmm, what do you know: https://technet.microsoft.com/en-us/sysinternals/bb897438.aspx  do you think this is the most promising way forward?

**Comment by snoyberg** [comment]
I really don't know, this is beyond my area of expertise.
