### ISSUE TITLE
trouble getting MinGHC to work correctly

### ISSUE THREAD

**Issue by hanjoosten** [fpco/minghc#91]
I have installed MinGHC as logged [here](https://github.com/AmpersandTarski/TheToolsWeUse/blob/master/haskell.md).

ghc seems to do it's job ok, but finally I get the following error message:

```
Linking dist/dist-sandbox-1983fae3\build\ampersand\ampersand.exe ...
ghc.exe: could not execute: C:\Users\hjo20125\AppData\Local\Programs\minghc-7.10
.2-x86_64\ghc-7.10.2\lib/../mingw/bin/gcc.exe
cabal: Error: some packages failed to install:
ampersand-3.2.0 failed during the building phase. The exception was:
ExitFailure 1
```

Some looking around, I see that I have two versions of gcc on my system. Both of mingw, but from different versions. However, the one added to my system is the one up front in the path. Note that this only happens at link-time. ghc itself already built everything.

Now what to do??

**Comment by hanjoosten** [comment]
Could it be that the combination of backward/forward slashes in the path breaks anything? The executable [builds fine on travis](https://travis-ci.org/AmpersandTarski/ampersand/builds/81143727)

Anyone has some suggestions?

**Comment by 3noch** [comment]
Very strange. Have you tried building with stack? Stack uses a more isolated environment and might avoid this issue.

**Comment by hanjoosten** [comment]
Yes, I have looked at stack, but not all of [the packages that I use](https://github.com/AmpersandTarski/ampersand/blob/upgrade_to_haskell_7.10/ampersand.cabal) are available in stack. So unfortunately, that doesn't seem an option. Also, I am not very familiar to stack yet. 
For the error I get, I doubt that it has anything to do with having specific versions of packages. Everything compiles smoothly. Only when the link process starts, ghc.exe complains that it cannot execute gcc. The path ghc mentions in the error message, is 100% correct. Only there is a mix of backslash and lsash in the path. 
Would it be possible to log anything? Could I for instance find out if ghc cannot find gcc.exe, or that it can find gcc.exe, but gcc.exe throws some error?

**Comment by hanjoosten** [comment]
I found [this thread at Stackoverflow](http://stackoverflow.com/questions/31194891/haskell-stack-build-error-ghc-exe-could-not-execute). It seems to suggest that there is something wrong with the slashes, also using stack. Is this something in ghc? Is this the right place to file this issue?

**Comment by hanjoosten** [comment]
There is an issue with gcc.exe. Using a newer version will likely solve this problem, which seems to have to do with long pathnames (yes, I use a sandbox..) 
[This ticket](https://ghc.haskell.org/trac/ghc/ticket/10726) is raised at ghc

**Comment by hanjoosten** [comment]
More on this issue can be found in [this thread](https://github.com/commercialhaskell/stack/issues/466).

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported. Seems like that's where you are going anyway.
