### ISSUE TITLE
MinGW and gfortran problem

### ISSUE THREAD

**Issue by varosi** [fpco/minghc#92]
MinGHC 7.10.2 x64, Windows 10 x64

I'm trying to build OpenBLAS that way:
1. Install MinGHC 7.10.2 in folder without spaces
2. Clone OpenBLAS (https://github.com/xianyi/OpenBLAS.git)
3. mingw32-make in OpenBLAS root

I got:

 > gfortran: error: CreateProcess: No such file or directory

while building it. So I found that problem on Stackoverflow:
http://stackoverflow.com/questions/28599135/gfortran-error-createprocess-no-such-file-or-directory-in-build-with-mingw

They state that the problem could be in not correctly installed Mingw.

**Comment by snoyberg** [comment]
The mingw shipped with minghc doesn't have Fortran as far as I know. It's
shipped with GHC specifically for building Haskell code. You'll likely need
to get a separate mingw install.

**Comment by varosi** [comment]
Check this executable:
minghc-7.10.2-x86_64\ghc-7.10.2\mingw\bin\gfortran.exe

**Comment by 3noch** [comment]
It's worth noting that the mingw that ships with GHC is never added to your `PATH`. GHC uses it privately with relative paths. If you actually want your build process to find anything in that folder, you likely need to add it to your `PATH`.

**Comment by ndmitchell** [comment]
We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
