### ISSUE TITLE
how to like ghci that can load haskell script first and then run functions in console like ghci

### ISSUE THREAD

**Issue by LovelyYanki** [fpco/minghc#97]
how to like ghci that can load haskell script first and then run functions in console like ghci

as i have some functions are still testing, not ready be part of script

and do not want to edit and load script many times, 

i type ghci, it do not have console environment, do it have ghci?

**Comment by ndmitchell** [comment]
Are you looking for `runhaskell`? If you do `runhaskell Main.hs` that runs a Haskell file.

**Comment by LovelyYanki** [comment]
my intel compute stick left less than 1 GB, but haskell platform is so large.
i expect console like
ghci > :l hello.hs

and then test run some frequently edited function which will use the functions in hello.hs for testing by copy and paste
to console

**Comment by ndmitchell** [comment]
That should work. If you have 1Gb you may be out of luck though - MinGHC refers to a small number of packages we ship with, but it's still 1.2Gb on my machine.

**Comment by ndmitchell** [comment]
I suggest you either ask on StackOverflow or http://reddit.com/r/haskell - both might contain information about how to work with such little memory.

We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.
