### ISSUE TITLE
Change repo description to start with "DEPRECATED" or something

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#99]
Make it easy to see when scanning a bunch of repos.

**Comment by ndmitchell** [comment]
Good idea - do you not have permission to do that @3noch?

**Comment by 3noch** [comment]
Ha, apparently not. Hence the issue. :)

**Comment by snoyberg** [comment]
I added DEPRECATED, and gave both of you admin rights. I learnt two things: (1) I'd only given you write access before, likely due to old limitation in Github perms, and (2) you need admin access to change a repo description.

**Comment by 3noch** [comment]
👏
